export default StringConstants = {
    // ONBOARDING SCREEN
    REGISTER_NOW: ' Register Now.',
    LOGIN: 'LOGIN',
    LOG_IN: 'LOG IN',
    REGISTERED_EMAIL: 'Registered Email Id',
    ACTIVATION_CODE: 'Activation Code',
    RESET: 'RESET',
    UPDATE: 'UPDATE',
    HAVE_ACCOUNT: 'Have an account ?',
    FORGOT_PASSWORD_LOGIN: 'Forgot Password ?',
    EMAIL: 'Email Id',
    PASSWORD: 'Password',
    NEW_PASSWORD: 'New Password',
    CONFIRM_PASSWORD: 'Confirm Password',
    SELECT_GENDER:'Select Gender',
    SELECT_COUNTRY:'Select Country',
    ENTER_YOUR_EMAIL: 'Enter the email address of a friend, to join GodConnect',
    ENTER_YOUR_USERNAME: 'Enter your username',
    ENTER_YOUR_PASSWORD: 'Enter your password',
    ENTER_NEW_PASSWORD: 'Enter new password',
    ENTER_CONFIRM_NEW_PASSWORD: 'Enter confirm new password',
    DONT_HAVE_ACCOUNT: 'Don’t have an account?',
    ALREADY_HAVE_AN_ACCOUNT: 'Already have an account?',
    BACK: 'Back',
    SIGN_UP: 'SIGN_UP',
    SIGNUP: 'SIGN UP',
    FULL_NAME: 'Full Name',
    CONTACT_NO: 'Contact Number',
    FRIEND_REQUEST: 'Friend Request',
    YOUR_FRIEND: 'Your Friends',
    SCHEDULE_EVENT:'Schedule Event',
    CONTINUE: 'Continue',
    DONE: 'Done',
    RESET_PASSWORD: 'RESET PASSWORD',
    FORGOT_PASSWORD: 'FORGET PASSWORD',
    SUBMIT: 'Submit',
    VERIFICATION_CODE: 'Verification Code',
    CODE_HAS_BEEN_SENT: 'A 6 digit code has been sent to ',
    LOGOUT: 'Logout',
    LOGOUT_WARNING: 'Are you sure you want to log out?',
    BY_SIGNING_UP: 'By signing up you agree to our ',
    TERMS_OF_SERVICE: 'Terms of Service ',
    AND: 'and ',
    PRIVACY_POLICY: 'Privacy Policy',
    ONE_TIME_EVENT: 'One Time Event',
    // MENU TAB 
    MENU: 'Menu',
    YOUR_PROFILE: 'Your Profile',
    GROUPS: 'Groups',
    EVENTS: 'Events',
    MARKET: 'MarketPlace',
    FRIEND: 'Friends',
    CHAT: 'Chat',
    INVITE: 'Invite',
    PRAYER: 'Prayer',
    CHURCH: 'Church Near By',

    // MARKETPLACE TAB
    CATEGORY: "Category",
    CUSTOMIZATIONS: "Customization",
    DISHES: "Dishes",

    // SETTINGS TAB
    SETTINGS_HEADING: 'Settings',
    PAYMENT_CONFIG: 'Payment Config',
    EDIT_PAYMENT_CONFIG: 'Edit Payment Config',
    COVID_19_VACCINATION: 'Covid-19 Vaccination',
    REQUIRE_COVID_19_VACCINATION: 'Require Covid-19 Vaccination',
    LABEL_CLIENT_ID: 'Client ID',
    LABEL_CLIENT_SECRET: 'Client Secret',
    LABEL_MERCHANT_KEY: 'Merchant Key',
    PLACEHOLDER_PASSWORD: '******',
    BUTTON_YES: 'Yes',
    BUTTON_NO: 'No',
    BUTTON_CONFIRM: 'Confirm',
    BUTTON_DELETE: 'Delete',
    BUTTON_UNFRIEND: 'Unfriend',
    BUTTON_CATEGORIES: 'Categories',
    // CREATEPOST
    PUBLISH: 'PUBLISH',
    SAVE: 'SAVE',
    FIRST_NAME: 'First Name',
    LAST_NAME: 'Last Name',
    EMAIL_ADDRESS: 'Email Address',
    MOBILE_NUMBER: 'Mobile Number',
    TYPE: 'Type',
    INVITE_FRIEND: 'INVITE',
    CANCEL: 'CANCEL',
    JOIN: 'Join Now',
    ADVERTISE: 'Advertisments',
    FRIEND_SUGGESTION: 'Friend Suggestion',
    ADD_FRIEND: 'Add Friend',
    REMOVE: 'Remove',
    MESSAGE: 'Message',
    EDIT_PROFILE: 'Edit Profile',


    //VALIDATIOS ALERT

    PLEASE_ENTER_YOUR_USERNAME: 'Please enter your username',
    PLEASE_ENTER_YOUR_EMAIL_ID: 'Please enter your email id',
    PLEASE_ENTER_YOUR_PASSWORD: 'Please enter your password',
    PLEASE_ENTER_A_VALID_EMAIL_ID: "Please enter a valid email id",
    PLEASE_ENTER_YOUR_NEW_PASSWORD: 'Please enter your new password',
    PASSWORD_DOESNOT_MATCH: 'Password does not match.',
    PASSWORD_LENGTH_MUST_BE_GREATER_THAN_6_DIGITS: 'Password length must be greater than 6 digits',
    PASSWORD_SHOUD_NOT_CONTAIN_WHITESPACES: 'Password should not contain whitespaces.',
    PASSWORD_UPDATED_SUCCESSFULLY: "Password updated successfully",
    PLEASE_ACCEPT_TERMS: 'Please agree to the Terms and Conditions',
    ENTER_OTP: "Please Enter Verification Code.",
    VERIFICATION_CODE_6_DIGIT: "The verification code must be a six digit code.",
    INAVLID_OTP_CODE: "Inavlid OTP code",
    THE_EMAIL_IS_NOT_REGISTERED_WITH_US: 'The email is not registered with us.',
    CHECK_INTERNET: 'Something went wrong.'

}